# Generated by Django 5.2.1 on 2025-06-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="auther",
            new_name="author",
        ),
    ]
